import 'package:json_annotation/json_annotation.dart';
import 'package:scoped_model/scoped_model.dart';
///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
///
part 'session_model.g.dart';
@JsonSerializable()
class SessionModelsDataGroups {


  int id;
  int user_id;
  String name;
  String created_at;
  String info;
  String avatar;
  int is_pwd;
  int hot;

  SessionModelsDataGroups(
    this.id,
    this.user_id,
    this.name,
    this.created_at,
    this.info,
    this.avatar,
    this.is_pwd,
    this.hot,
  );

  factory SessionModelsDataGroups.fromJson(Map<String,dynamic> json) => _$SessionModelsDataGroupsFromJson(json);

  Map<String,dynamic> toJson() => _$SessionModelsDataGroupsToJson(this);

}

@JsonSerializable()
class SessionModelsDataUsers
{


  int id;
  String name;
  String email;
  String avatar;
  int status;
  String bio;
  int sex;
  int client_type;
  int age;
  String last_login_time;


  SessionModelsDataUsers(
    this.id,
    this.name,
    this.email,
    this.avatar,
    this.status,
    this.bio,
    this.sex,
    this.client_type,
    this.age,
    this.last_login_time,
  );

  factory SessionModelsDataUsers.fromJson(Map<String,dynamic> json) => _$SessionModelsDataUsersFromJson(json);

  Map<String,dynamic> toJson() => _$SessionModelsDataUsersToJson(this);

}

@JsonSerializable()
class SessionModelsData {


  int id;
  int form_id;
  int to_id;
  int group_id;
  String created_at;
  int top_status;
  String top_time;
  String note;
  int channel_type;
  String name;
  String avatar;
  int status;

  @JsonKey(nullable: true)
  SessionModelsDataUsers Users;

  @JsonKey(nullable: true)

  SessionModelsDataGroups Groups;


  SessionModelsData(
    this.id,
    this.form_id,
    this.to_id,
    this.group_id,
    this.created_at,
    this.top_status,
    this.top_time,
    this.note,
    this.channel_type,
    this.name,
    this.avatar,
    this.status,
    this.Users,
    this.Groups,
  );

  factory SessionModelsData.fromJson(Map<String,dynamic> json) => _$SessionModelsDataFromJson(json);

  Map<String,dynamic> toJson() => _$SessionModelsDataToJson(this);

}

@JsonSerializable()
class SessionModels extends Model {

  int code;
  String message;

  @JsonKey(nullable: true)
  List<SessionModelsData> data;
  int HttpCode;

  SessionModels(
    this.code,
    this.message,
    this.data,
    this.HttpCode,
  );

  factory SessionModels.fromJson(Map<String,dynamic> json) => _$SessionModelsFromJson(json);

  Map<String,dynamic> toJson() => _$SessionModelsToJson(this);
}
